repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: no-commit-to-branch  # prevent direct commits to main branch
    - id: check-yaml
      args: ['--unsafe']
    - id: check-toml
    - id: trailing-whitespace
    - id: end-of-file-fixer
