[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "greeter_project"
version = "1.0.0"
dependencies = [
    "art==6.2",
]

[project.optional-dependencies]
dev = [
    "pytest==8.2.0",
    "hypothesis==6.100.5",
]
