name: Generate PDF
on:
  push:
    branches: [2023-pycon-de*]

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: 2023_PyData_Berlin/environment.yml
        activate-environment: 2023_PyData_Berlin
    - name: Generate PDF
      shell: bash -el {0}
      run:
        python 2023_PyData_Berlin/src/assemble_plots.py
    - name: Archive PDF
      uses: actions/upload-artifact@v3
      with:
        name: galery.pdf
        path: 2023_PyData_Berlin/results/galery.pdf
